### ISSUE TITLE
Implement key import from geth keystore

### ISSUE THREAD

**Issue by tinybike** [AugurProject/keythereum#1]
Export is implemented, but not import.

**Comment by SilentCicero** [comment]
+1

**Comment by SilentCicero** [comment]
What is the timeline on key import?

**Comment by tinybike** [comment]
Whenever I get a break from putting out fires -- should be the next day or two!

**Comment by tinybike** [comment]
Implemented in f8670d589cfd6ff95681e5f24d0bab58b8b095f0.
